### ISSUE TITLE
Fence Gate crash

### ISSUE THREAD

**Issue by cheezitbomb** [Bunsan/TechNodeFirmaCraft#2] opened 2015-03-02 20:33 UTC
I built the fenced area then had two open spaces to have fence gates side by side so I could get horses into the pen area. In Multiplayer I place the first fence gate fine but when I try placing the second fence gate my client crashes out. In Singleplayer it crashed me on the first one I tried placing. The fence on one side of the two space gap was a corner post, the fence on the other side of the gap was not.

Multiplayer Client crash report
http://pastebin.com/zY6w7Cx0

Server Console
http://pastebin.com/9czBcCZR

Singleplayer Client crash report
http://pastebin.com/TjGkaR6w

**Comment by Bunsan** [comment] 2015-03-02 21:13
I've pushed the fix, but you can just do it yourself. In the config folder, go to the railcraft folder and open up the blocks.cfg. Change the value for the residual heat block to false. This is the hidden Railcraft block and is the cause of the crash.

**Closed as completed by Bunsan** 2015-03-02 21:13 UTC
